### ISSUE TITLE
refactor monolith module into multiple

### ISSUE THREAD

**Issue by ayushin** [djangoflow/terraform-kubernetes-django#6]
We need to refactor the functionality between different modules and split them into separate repositories so that we can have fine grained control of ingress, databases, storage and dns at the project level.

This repository can be one of the standard cases how to use those modules in concerto, we should also create examples how to customise deployment to finer details.

**Comment by magusd** [comment]
hey there @ayushin,

I'm thinking of doing a heroku-like approach to those attached resources by handling them as `addons`.

instead of using the terraform module like this:

```terraform
module "app_01" {
  source       = "git@github.com:djangoflow/terraform-kubernetes-django?ref=main"
  ...
  postgres_enabled = true
  postgres_storage_size = 10Gi
  postgres_resources_requests_memory = 256Mi
  postgres_resources_requests_cpu = 250m
  ...
}
```

we would use it like this:

```terraform
module "app_01" {
  source       = "git@github.com:djangoflow/terraform-kubernetes-django?ref=main"
  //...
  addons = {
      db = {
           addon_type = "kubernetes_postgres"
           storage = "10Gi"
           memory = "256Mi"
           cpu = "250m"
           memory_limit = null
           cpu_limit = null
      }
  }
  //...
}
```

which would allow us to generalize the application provisioning by wrapping most of the data in a yaml file like so

```yaml
app:
   addons:
       db:
           type: "kubernetes.postgres"
           storage: "10Gi"
           cpu: "250m"
           memory: "256Mi"
       bucket:
           type: "gcp.bucket"
           name: files.demo.djangoflow.com
           public_storage: true # uses the dns module under the hood
       ingress:
           type: "kubernetes.ingres"
           ruleset: {
                # uses the dns module under the hood
                "api.demo.djangoflow.com": {
                         "/": "api"
                 }
       # same idea for {"kubernetes.redis","gcp.database","aws.s3"}
```

and using that with terraform would be:

```terraform
module "app_01" {
  source       = "git@github.com:djangoflow/terraform-kubernetes-django?ref=main"
  //...
  addons = yamldecode("${path.cwd}/app.yaml")
  //...
}
```

To achieve that I'd just move the project files into the appropriate modules, I'd push back against the idea of having all of those modules as different repositories as that would create unnecessary chore. 

We can always easily extract modules if we ever need to reuse them, or we could just allow other project to pull the modules directly from this repo using

```terraform
module "kubernetes_database" "db" {
source = "git@github.com:djangoflow/terraform-kubernetes-django.git//modules/postgres?ref=v1.2.3"
}
```
or even publishing those modules as independent modules by using a hosted registry.

How does that sound?
